hosts:
  sshportal:
    HostName: 127.0.0.1
    Port: 2222
    Hook: {}
    User: admin

  github.com:
    Hook:
      OnConnect: []

  altgithub.com:
    HostName: github.com

  "*.127.0.0.1.xip.io":
    user: moul

defaults:
  ControlMaster: auto
  ControlPath: ~/.cache/ssh/%C.sock
  ControlMasterMkdir: true
  ControlPersist: yes
  Compression: yes
  LogLevel: ERROR
  ServerAliveInterval: 5
  ServerAliveCountMax: 18
  #UseKeychain: yes
  #AddKeysToAgent: yes
  VisualHostKey: yes
  HashKnownHosts: yes
  VerifyHostKeyDNS: ask
  SetEnv:
    - LC_ALL=en-US.UTF-8
    - LANG=en_US.UTF-8
  Hooks:
    BeforeConfigWrite: []
    AfterConfigWrite: []
    OnConnect: []
    OnDisconnect: []
